### ISSUE TITLE
bug on utf-8

### ISSUE THREAD

**Issue by RuiPMoreira** [aichaos/rivescript#3]
hey,

I think that i found a bug on utf-8
Check this example:
https://play.rivescript.com/s/sQv6391jAF

Ty

**Comment by kirsle** [comment]
It's a known issue when using optionals with unicode. There's a longer discussion here: https://github.com/aichaos/rivescript-js/issues/147

I plan to fix it eventually by adding a `~Regexp` command to the language that allows you to define a trigger by manually providing the regexp. You can track that issue here: https://github.com/aichaos/rivescript-wd/issues/6
